### ISSUE TITLE
Unable to release with require PR before merging

### ISSUE THREAD

**Issue by luukvhoudt** [ScientaNL/eslint-plugin#2]
- [Failing action](https://github.com/ScientaNL/eslint-plugin/actions/runs/5748303404/attempts/1)
- [Related SA question](https://stackoverflow.com/questions/74128344/)

**Comment by luukvhoudt** [comment]
Possible fix, add `permissions` to the job:

```yaml
permissions:
  contents: read
  pull-requests: write
  issues: write
  actions: write
```
